name: Fetch and Update UUP Data

on:
  schedule:
    - cron: '0 */2 * * *'  # Her 2 saatte bir çalışır

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PowerShell
        uses: actions/setup-powershell@v3
        with:
          powershell-version: '7.4.1'

      - name: Download PowerShell Script and Data
        run: |
            wget https://raw.githubusercontent.com/bensuslu11/UUP_Downloader_API/main/uup_data_fetch.ps1 -O uup_data_fetch.ps1
      
      - name: Execute PowerShell script
        run: pwsh ./uup_data_fetch.ps1 -OutputPath ./uup_data.json

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Updated UUP data'
          file_pattern: uup_data.json