name: Fetch Windows Version Data

on:
  schedule:
    - cron: '0 */2 * * *'  # Her 2 saatte bir çalışır
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm install
          npm install -g npm@latest
        
      - name: Fetch and update data
        run: npm run fetch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./data
          publish_branch: gh-pages
          commit_message: "Update Windows version data"